### ISSUE TITLE
Final group capstone: Set up your Kanban board

### ISSUE THREAD

**Issue by rubydevi** [rubydevi/jetlogix-backend#14]
## Description
We have prepared a [Kanban board](https://github.com/rubydevi/jetlogix-backend/projects/1) for the Final Group Capstone according to this [Project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md#project-requirements).

## Team
We are a team of 3
- Student A: @Yonashenok 
- Student B: @RileyManda 
- Student C: @rubydevi 

## Screenshot of our Kanban
![image](https://github.com/rubydevi/jetlogix-backend/assets/112550568/a877a136-d14e-4813-8868-68b5b7aec9e6)

**Comment by Meltrust** [comment]
Hi @rubydevi,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks have assignees, descriptions, and pointings according to spec ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rubydevi** [comment]
@Meltrust Thank you so much 🙏
